-- Fix missing 'vehicles' table and enable RLS

-- 1. Create vehicles table if it doesn't exist
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT NOT NULL,
    model TEXT,
    brand TEXT,
    color TEXT,
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS on all tables
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- 3. Add basic policy for vehicles (so you can use it)
DROP POLICY IF EXISTS "Authenticated users can do everything on vehicles" ON vehicles;
CREATE POLICY "Authenticated users can do everything on vehicles" ON vehicles FOR ALL TO authenticated USING (true) WITH CHECK (true);
