-- FULL SCHEMA SETUP FOR CARWASH SAAS
-- Run this script in the Supabase SQL Editor to set up the entire database.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- Customers
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Vehicles
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT NOT NULL,
    model TEXT,
    brand TEXT,
    color TEXT,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Services
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    description TEXT,
    commission DECIMAL(10, 2) DEFAULT 0, -- Fixed commission amount
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Employees
CREATE TABLE IF NOT EXISTS employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Nullable for unlinked employees
    name TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'employee')) DEFAULT 'employee',
    pin TEXT, -- For simple login
    commission_rate DECIMAL(10, 2) DEFAULT 0, -- Percentage (0.30 = 30%)
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Transactions (Sales)
CREATE TABLE IF NOT EXISTS transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    vehicle_id BIGINT REFERENCES vehicles(id),
    service_id BIGINT REFERENCES services(id),
    employee_id UUID REFERENCES employees(id), -- Main employee (legacy/primary)
    price NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, completed, paid, waiting, in_progress
    payment_method TEXT DEFAULT 'cash',
    tip DECIMAL(10, 2) DEFAULT 0,
    commission_amount DECIMAL(10, 2) DEFAULT 0,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    extras JSONB DEFAULT '[]'::jsonb -- Store extras as JSON
);

-- Transaction Assignments (Multi-Employee Support)
CREATE TABLE IF NOT EXISTS transaction_assignments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Expenses
CREATE TABLE IF NOT EXISTS expenses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    description TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('product', 'lunch')),
    employee_id UUID REFERENCES employees(id),
    date TIMESTAMPTZ DEFAULT timezone('America/Puerto_Rico'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. STORAGE (Receipts)
INSERT INTO storage.buckets (id, name, public)
VALUES ('receipts', 'receipts', true)
ON CONFLICT (id) DO NOTHING;

-- 4. ROW LEVEL SECURITY (RLS)

-- Enable RLS
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Authenticated users can read/write most things for now)
CREATE POLICY "Authenticated users can do everything on customers" ON customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can do everything on vehicles" ON vehicles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can do everything on services" ON services FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Employee Policies
CREATE POLICY "Admins manage employees" ON employees FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM employees WHERE user_id = auth.uid() AND role = 'admin'));
CREATE POLICY "Everyone reads employees" ON employees FOR SELECT TO authenticated USING (true);

-- Transaction Policies (Complex)
-- Admin sees all
CREATE POLICY "Admins see all transactions" ON transactions FOR ALL USING (auth.uid() IN (SELECT user_id FROM employees WHERE role = 'admin'));

-- Employees see own + waiting
CREATE POLICY "Employees see own transactions" ON transactions FOR SELECT USING (
  auth.uid() IN (SELECT user_id FROM employees WHERE role = 'admin') OR
  status = 'waiting' OR
  employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()) OR
  id IN (SELECT transaction_id FROM transaction_assignments WHERE employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()))
);

-- Insert
CREATE POLICY "Users can insert transactions" ON transactions FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Update
CREATE POLICY "Users can update transactions" ON transactions FOR UPDATE USING (
  auth.uid() IN (SELECT user_id FROM employees WHERE role = 'admin') OR
  status = 'waiting' OR
  employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()) OR
  id IN (SELECT transaction_id FROM transaction_assignments WHERE employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()))
);

-- Transaction Assignments Policies
CREATE POLICY "Admin ve todas las asignaciones" ON transaction_assignments FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM employees WHERE user_id = auth.uid() AND role = 'admin'));
CREATE POLICY "Empleados ven sus asignaciones" ON transaction_assignments FOR SELECT TO authenticated USING (employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()));
CREATE POLICY "Crear asignaciones" ON transaction_assignments FOR INSERT TO authenticated WITH CHECK (true);

-- Expenses Policies
CREATE POLICY "Admins can do everything on expenses" ON expenses FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM employees WHERE user_id = auth.uid() AND role = 'admin'));
CREATE POLICY "Employees can view their own lunches" ON expenses FOR SELECT TO authenticated USING (employee_id IN (SELECT id FROM employees WHERE user_id = auth.uid()));

-- Storage Policies
CREATE POLICY "Public Access Receipts" ON storage.objects FOR SELECT USING ( bucket_id = 'receipts' );
CREATE POLICY "Authenticated Uploads Receipts" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'receipts' and auth.role() = 'authenticated' );

-- 5. SEED DATA (Optional)
INSERT INTO services (name, price, commission) VALUES
  ('Lavado Simple', 10, 3),
  ('Lavado Premium', 20, 5),
  ('Detallado Interior', 50, 15)
ON CONFLICT DO NOTHING;

-- Create initial Admin (You must link this to a real user later)
-- INSERT INTO employees (name, role, pin, commission_rate) VALUES ('Admin', 'admin', '0000', 0);
