-- ==========================================
-- CARWASH SAAS - FULL INSTALLATION SCRIPT
-- ==========================================
-- SCRIPT DE INSTALACIÓN COMPLETA PARA NUEVOS CLIENTES
-- Copia y corre esto en el SQL Editor de tu nuevo proyecto Supabase.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- Customers
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    points INTEGER DEFAULT 0,
    vehicle_plate TEXT, -- Legacy
    vehicle_brand TEXT, -- Legacy
    vehicle_model TEXT, -- Legacy
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Vehicles (Multi-vehicle support)
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT NOT NULL,
    model TEXT,
    brand TEXT,
    color TEXT,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Services
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    description TEXT,
    commission DECIMAL(10, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Employees
CREATE TABLE IF NOT EXISTS employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Links to Supabase Auth User
    name TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'manager', 'employee')) DEFAULT 'employee',
    pin TEXT,
    commission_rate DECIMAL(10, 2) DEFAULT 0,
    email TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Business Settings (White-Label)
CREATE TABLE IF NOT EXISTS business_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT
);

-- Transactions (Sales)
CREATE TABLE IF NOT EXISTS transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    vehicle_id BIGINT REFERENCES vehicles(id),
    service_id BIGINT REFERENCES services(id),
    employee_id UUID REFERENCES employees(id), -- Primary employee
    price NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, waiting, in_progress, ready, completed, paid, cancelled
    payment_method TEXT DEFAULT 'cash',
    tip DECIMAL(10, 2) DEFAULT 0,
    commission_amount DECIMAL(10, 2) DEFAULT 0,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    extras JSONB DEFAULT '[]'::jsonb
);

-- Transaction Assignments (Multi-Employee)
CREATE TABLE IF NOT EXISTS transaction_assignments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Expenses
CREATE TABLE IF NOT EXISTS expenses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    description TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('product', 'lunch', 'other')),
    employee_id UUID REFERENCES employees(id),
    date TIMESTAMPTZ DEFAULT timezone('America/Puerto_Rico'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Daily Notes / Chat
CREATE TABLE IF NOT EXISTS daily_notes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    content TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Memberships
CREATE TABLE IF NOT EXISTS memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    wash_limit INTEGER DEFAULT 9999, -- 9999 = Unlimited
    type TEXT DEFAULT 'monthly', -- monthly, annual
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customer_memberships (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    membership_id BIGINT REFERENCES memberships(id),
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    status TEXT DEFAULT 'active', -- active, cancelled, expired
    usage_count INTEGER DEFAULT 0,
    last_usage_date DATE,
    auto_renew BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Customer Feedback
CREATE TABLE IF NOT EXISTS customer_feedback (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    transaction_id UUID REFERENCES transactions(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);


-- 3. STORAGE SETUP
INSERT INTO storage.buckets (id, name, public) VALUES ('receipts', 'receipts', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('branding', 'branding', true) ON CONFLICT (id) DO NOTHING;


-- 4. ENABLE RLS
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_feedback ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES (Simplified for new install: Authenticated users = Staff)

-- Public Access (App needs these open for some features)
-- NOTE: For production, you might want to restrict these further, but for quick launch this is safe enough if signup is disabled.
CREATE POLICY "Public Read Settings" ON business_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Services" ON services FOR SELECT USING (true);

-- Authenticated Access (Staff/Admin)
CREATE POLICY "Staff Full Access Customers" ON customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Vehicles" ON vehicles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Services" ON services FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Employees" ON employees FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Settings" ON business_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Transactions" ON transactions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Assignments" ON transaction_assignments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Expenses" ON expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Notes" ON daily_notes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Memberships" ON memberships FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access CustMemberships" ON customer_memberships FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff Full Access Feedback" ON customer_feedback FOR SELECT TO authenticated USING (true); -- Read only
CREATE POLICY "Staff Insert Feedback" ON customer_feedback FOR INSERT TO authenticated WITH CHECK (true);

-- Public/Customer Access specific
-- Allow public to INSERT feedback (assuming they have the link)
CREATE POLICY "Public Feedback Insert" ON customer_feedback FOR INSERT WITH CHECK (true);

-- Storage Policies
-- Assuming 'storage.objects' is the table. In some Supabase versions you need to enable the extension in schema.
create policy "Authenticated Receipts Upload" on storage.objects for insert with check ( bucket_id = 'receipts' and auth.role() = 'authenticated' );
create policy "Public Receipts Read" on storage.objects for select using ( bucket_id = 'receipts' );

create policy "Authenticated Branding Upload" on storage.objects for insert with check ( bucket_id = 'branding' and auth.role() = 'authenticated' );
create policy "Public Branding Read" on storage.objects for select using ( bucket_id = 'branding' );
create policy "Authenticated Branding Update" on storage.objects for update with check ( bucket_id = 'branding' and auth.role() = 'authenticated' );


-- 6. DEFAULT DATA

-- Branding Defaults
INSERT INTO business_settings (setting_key, setting_value) VALUES 
('business_name', 'Nombre de Tu CarWash'),
('business_logo_url', '/logo.jpg'),
('is_open', 'true')
ON CONFLICT (setting_key) DO NOTHING;

-- Default Services
INSERT INTO services (name, price, commission) VALUES
('Lavado Básico (Sedan)', 15.00, 4.00),
('Lavado Básico (SUV)', 20.00, 5.00),
('Lavado Premium', 35.00, 10.00)
ON CONFLICT DO NOTHING;
