-- Create tables for Carwash SaaS

-- Customers Table
create table customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Vehicles Table
create table vehicles (
  id bigint generated by default as identity primary key,
  plate text not null,
  model text,
  brand text,
  color text,
  customer_id bigint references customers(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Services Table
create table services (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sales/Orders Table
create table sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id),
  vehicle_id bigint references vehicles(id),
  service_id bigint references services(id),
  total numeric not null,
  status text default 'pending', -- pending, completed, paid
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed initial services
insert into services (name, price) values
  ('Lavado Simple', 10),
  ('Lavado Premium', 20),
  ('Detallado Interior', 50);
